name: Usage issues
description: Report issues in usage.
title: "[Usage] "
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form.  Please give as detailed description as possible for us to better assist with the issue :)
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "Issue"
    validations:
      required: true
  - type: textarea
    id: command-log
    attributes:
      label: Command and logs
      description: The command that you use which triggered this error.  Please paste the **FULL** error log here, so that we can better understand the issue. Wrap the log with ``` for better readability in GitHub.
      placeholder: Command and logs
      value: |
        Command:
        Log: 
        ```
        PASTE THE LOGS HERE.
        ```
    validations:
      required: true
  - type: dropdown
    id: clone-date
    attributes:
      label: When did you clone our code?
      options:
        - I cloned the code base after 5/1/23
        - I cloned the code base before 5/1/23, but have pulled the latest code base
        - I cloned the code base before 5/1/23, and have not upgraded yet
    validations:
      required: true
